[package]
name = "frame-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Reusable UI components for Frame"

[dependencies]
iced = { workspace = true, features = ["canvas"] }
iced_aw = { workspace = true }
frame-core = { path = "../../packages/core", default-features = false }
